#+TITLE: Org Mode Demo
#+STARTUP: indent
#+OPTIONS: num:nil
#+BEGIN_EXPORT html
---
title: "El Inicio de la Comunidad Familia de Dios"
description: "Historia de como inicia el movimiento Comunidad Familia de Dios"
menuGoes: true
menu:
  -
    queDice: Página Principal
    dir: ""
    especial: false
    externa: false
  -
    queDice: Sobre Nosotros
    dir: sub/nosotros
    especial: false
    externa: false
  -
    queDice: Acción
    dir: sub/alcance
    especial: false
    externa: false
  -
    queDice: ¡Contáctanos!
    dir: contacto
    especial: true
    externa: false
---
#+END_EXPORT

* NUESTROS INICIOS
En 1994 al concluir José Luis y Betty de Martinez (+) su encargo de Coordinadores Generales de la Renovación Carismática Católica en el Espíritu Santo (RCCES) de la Diócesis de Monterrey y considerando una moción del Espíritu Santo y la experiencia obtenida se proponen integrar verdaderas "Islas de Salvación" mediante Comunidades de Familia.

** El propósito: Evangelizar a sus propias Familias.
Lo anterior bajo la dirección y autoridad del Asesor de la RCCES de la Diócesis de Monterrey, el Padre David García Limón en ese tiempo. Se confirman las Comunidades de Familia durante la última estancia del Padre Emiliano Tardiff en Monterrey, N.L. (dos meses antes de su descanso eterno), quien se hospedó en la casa de José Luis y Betty; estando presentes el Padre Moisés Lárraga (Tambaca, S. L. P. ) e integrantes de la Comunidad de Familia.
Durante el encuentro le pidieron al Pbro. E. Tardiff que sugiriera el nombre de la misma, y dijo:
llámenle:

#+begin_quote
Comunidad Familia de Dios
#+end_quote

A partir de ese momento sucedieron tres acontecimientos muy importantes:
 - La consagración al Señor de nuestra Comunidad Familia de Dios.
 - El fortalecimiento de la unción del Espíritu Santo en el Padre Moisés Lárraga.
 - El principio de la sanación del cáncer en la médula de Betty Martínez;


