#+TITLE: Org Mode Demo
#+STARTUP: indent
#+OPTIONS: num:nil
#+BEGIN_EXPORT html
---
title: "Sobre Nosotros"
description: "Conoce más sobre la Comunidad Familia de Dios"
menuGoes: true
menu:
  -
    queDice: Pagina Principal
    dir: ""
    especial: false
    externa: false
  -
    queDice: Nuestros Inicios
    dir: sub/inicios
    especial: false
    externa: false
  -
    queDice: Acción
    dir: sub/alcance
    especial: false
    externa: false
  -
    queDice: ¡Contáctanos!
    dir: contacto
    especial: true
    externa: false
---
#+END_EXPORT

* ¿QUIENE SOMOS? Y ¿QUE HACEMOS?
*** “LA FAMILIA, OBJETO Y SUJETO DE EVANGELIZACIÓN”

** ¿QUE ES LO QUE HACE DIFERENTE A COMUNIDAD FAMILIA DE DIOS?.
Lo que hace diferente a COMUNIDAD FAMILIA DE DIOS es su dedicación total y absoluta en la formación integral de la Familia. Es decir, la obra se realiza con Papá, Mamá, Hijos y sus Familiares, no de manera aislada. El fin último es que en el hogar se hable el mismo idioma espiritual.

** NUESTRO OBJETIVO:
Es por eso que el objetivo de COMUNIDAD FAMILIA DE DIOS es: Evangelizar de una manera integral a la Familia, mediante la proclamación de la Buena Nueva o Kerygma (Recomenzando desde Cristo), en un Retiro (sin necesidad de enclaustrarse) de 1 ó 2 días, de preferencia sábado y/o domingo, pero se puede ajustar para ampliar o reducir su duración e impartirse durante una semana, en un día o día y medio. Se invita a la Familia completa o a personas que puedan invitar a formar Comunidad, a un familiar, de preferencia cercano, quien, posteriormente, deberá tomar el Retiro antes mencionado.

*** FORMACIÓN DE COMUNIDADES EN EL HOGAR:
Al término del Retiro se forman Comunidades de 6 a 8 parejas. Los hijos jóvenes se pueden reunir con sus Padres o Familiares para integrar una Comunidad o bien pasan a formar la Comunidad Familia de Dios de Jóvenes, Adolescentes o Niños.

*** CRECIMIENTO Y FORMACIÓN EN LA FE:
En un período de 6 a 8 meses, se les imparten Temas de Crecimiento sobre el manejo y lectura de la Biblia, así como Temas sobre la Familia. En este término se celebran 2 Retiros (sin necesidad de enclaustrarse): (i) uno denominado Formación de Discípulos, que tiene como objetivo principal la necesidad de tomar una decisión de servir al Señor, no meramente como un Evangelizado, sino como verdadero discípulo de Jesús, y; (ii) el segundo se denomina Formación de Predicadores, que tiene como objetivo la enseñanza y capacitación para predicarle primero a su Familia y luego a un auditorio mayor el Anuncio de la Buena Nueva o Kerygma .

*** LA FAMILIA, SUJETO DE EVANGELIZACIÓN:
Después del período anterior sigue un proceso de 4 meses en los cuales la Familia pasa de ser Objeto de Evangelización, para convertirse en Sujeto de la Evangelización. Cada Familia (Papá, Mamá, Hijos y Familiares) se sujeta a una representación o “casting” frente a sus Coordinadores de Comunidad, durante el cual desarrollarán un Tema del Retiro del Kerygma  o Seminario de Vida o Recomenzando desde Cristo; se hacen los ajustes a la predicación que los capacita para proclamar la Buena Nueva y “servir” en las Parroquias a donde se llama a COMUNIDAD FAMILIA DE DIOS. No se permite que inicie la predicación un solo miembro de la Familia, excepto que se trate de uno de sus hijos. Con el anterior “servicio” u “obra”, la Familia se convierte en Sujeto de la Evangelización e inicia una etapa de Misión Permanente en la Iglesia.

*** FAMILIAS MISIONERAS:
Durante la Semana Santa se invita a las Familias de las Comunidades a ir de Misiones ya sea “urbanas” o a diferentes Municipios de la Arquidiócesis y Estados. Se combina a las Familias de diversas Comunidades quienes salen de Misión a donde sea llamada COMUNIDAD FAMILIA DE DIOS, junto con los Jóvenes, Adolescentes y Niños, siendo éstos últimos, con sus Padres, los predicadores de la Buena Nueva o Kerygma en el Retiro, cada quien proclamando a los de su misma edad.

*** FAMILIA COORDINADORA DE COMUNIDAD:
Con el paso de un par de años, Papá y Mamá se conviertan en Coordinadores de otra COMUNIDAD FAMILIA DE DIOS, mientras que los Hijos y los Niños llevan igual proceso de formación. De esta forma, las Familias hablan un mismo “idioma”, el idioma del amor, del canto, de la alegría y, sobre todo, ser discípulos permanentes al servicio de su Iglesia y de sus Hermanos de manera integral.

*** SUJETOS A LA AUTORIDAD:
Con más de 22 años de existencia, COMUNIDAD FAMILIA DE DIOS está sujeta a la autoridad del Asesor Sacerdotal (a quien representamos en la Pastoral Familiar), Monseñor JOSÉ MANUEL GARZA MADERO, Obispo Auxiliar de Monterrey,. Todo servicio o acto se somete a su previa autorización.
